# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 14:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivatedRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_cmd', models.CharField(max_length=255, verbose_name='Kural Komutu')),
                ('operated_at', models.DateTimeField(default=datetime.datetime(2016, 6, 8, 17, 33, 35, 727841), verbose_name='Olu\u015fturulma Tarihi')),
                ('active_until', models.DateTimeField(default=datetime.datetime(2016, 6, 8, 17, 33, 35, 727878), verbose_name='Aktif Kalaca\u011f\u0131 Zaman')),
            ],
            options={
                'verbose_name': 'Aktif Edilmi\u015f Kural',
                'verbose_name_plural': 'Aktif Edilmi\u015f Kurallar',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Kaynak IP veya FQDN Bilgisi Giriniz(Tek)', max_length=80, verbose_name='Kaynak')),
                ('destination', models.CharField(help_text='Hedef IP veya FQDN Bilgisi Giriniz(Tek)', max_length=80, verbose_name='Hedef')),
                ('destination_port', models.IntegerField(help_text='Hedef Port Numaras\u0131n\u0131 Giriniz(Tek)', verbose_name='Hedef Port')),
                ('protocol', models.CharField(help_text='Protokol Bilgisini Giriniz(Tek)', max_length=80, verbose_name='Protokol')),
                ('time', models.IntegerField(help_text='Aktif Olaca\u011f\u0131 S\xfcreyi Dakika T\xfcr\xfcnden Giriniz(Tek)', verbose_name='S\xfcre')),
                ('fqdn', models.CharField(help_text='IP veya FQDN Giriniz(Tek)', max_length=80, verbose_name='G\xfcvenlik Duvar\u0131')),
                ('definition', models.CharField(help_text='Maksimum 255 Karakter', max_length=255, verbose_name='A\xe7\u0131klama')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Geli\u015ftirici')),
            ],
            options={
                'verbose_name': 'Kural',
                'verbose_name_plural': 'Kurallar',
            },
        ),
        migrations.AddField(
            model_name='activatedrule',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.Rule', verbose_name='Kural'),
        ),
    ]
